ALTER TABLE users ADD COLUMN password VARCHAR(255) AFTER nickname;
ALTER TABLE users MODIFY COLUMN provider ENUM('LOCAL', 'GITHUB', 'GOOGLE') NOT NULL;
ALTER TABLE users MODIFY COLUMN role ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER';
